const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const today=()=>new Date().toISOString().slice(0,10);const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
const state=JSON.parse(localStorage.getItem('finanx:data')||'{"debts":[],"expenses":[],"incomes":[],"investments":[]}');
function save(){localStorage.setItem('finanx:data',JSON.stringify(state));render()}
function debtStatus(d){if(d.paid)return'paid';return d.dueDate<today()?'overdue':'pending'}
function render(){const filter=$('#debtFilter').value;const debts=state.debts.filter(d=>filter==='all'||debtStatus(d)===filter);const overdue=state.debts.filter(d=>debtStatus(d)==='overdue'),pending=state.debts.filter(d=>debtStatus(d)==='pending'),paid=state.debts.filter(d=>debtStatus(d)==='paid');const sum=a=>a.reduce((t,x)=>t+Number(x.amount||0),0);const inv=sum(state.investments),exp=sum(state.expenses),inc=sum(state.incomes),debtOpen=sum([...overdue,...pending]),proj=inc-exp-debtOpen;
$('#overdueTotal').textContent=money(sum(overdue));$('#overdueCount').textContent=`${overdue.length} conta${overdue.length===1?'':'s'}`;$('#pendingTotal').textContent=money(sum(pending));$('#pendingCount').textContent=`${pending.length} conta${pending.length===1?'':'s'}`;$('#paidTotal').textContent=money(sum(paid));$('#paidCount').textContent=`${paid.length} conta${paid.length===1?'':'s'}`;$('#investmentTotal').textContent=money(inv);$('#investmentsTotal2').textContent=money(inv);$('#expensesTotal').textContent=money(exp);$('#incomeTotal').textContent=money(inc);$('#monthlyExpenseSummary').textContent=money(exp);$('#debtSummary').textContent=money(debtOpen);$('#projectedTotal').textContent=money(proj);$('#balanceLabel').textContent=money(proj);
let score=100;if(overdue.length)score-=Math.min(45,overdue.length*12);if(inc>0&&exp/inc>.7)score-=20;if(debtOpen>inc&&inc>0)score-=20;score=Math.max(0,score);$('#healthScore').textContent=score;
renderList($('#debtsList'),debts.map(d=>{const st=debtStatus(d);const installments=d.installment==='yes'?` • ${d.installments}x de ${money(Number(d.amount)/Number(d.installments||1))}`:'';return `<div class="list-item ${st}"><div><div class="item-title">${esc(d.name)}</div><div class="item-meta">Vence ${formatDate(d.dueDate)}${installments}${d.note?` • ${esc(d.note)}`:''}</div></div><div class="item-value">${money(d.amount)}<div class="item-meta">${st==='overdue'?'ATRASADO':st==='pending'?'A PAGAR':'PAGO'}</div></div><div class="item-actions">${!d.paid?`<button class="mini success" onclick="markPaid('${d.id}')">Marcar pago</button>`:''}<button class="mini danger" onclick="removeItem('debts','${d.id}')">Excluir</button></div></div>`}).join(''),'Nenhuma dívida encontrada.');
renderList($('#expensesList'),state.expenses.map(x=>`<div class="list-item"><div><div class="item-title">${esc(x.name)}</div><div class="item-meta">${esc(x.category)}</div></div><div class="item-value">${money(x.amount)}</div><div class="item-actions"><button class="mini danger" onclick="removeItem('expenses','${x.id}')">Excluir</button></div></div>`).join(''),'Nenhum gasto mensal cadastrado.');
renderList($('#investmentsList'),state.investments.map(x=>`<div class="list-item"><div><div class="item-title">${esc(x.name)}</div><div class="item-meta">${esc(x.type)}</div></div><div class="item-value">${money(x.amount)}</div><div class="item-actions"><button class="mini danger" onclick="removeItem('investments','${x.id}')">Excluir</button></div></div>`).join(''),'Nenhum investimento cadastrado.')}
function renderList(el,html,empty){el.innerHTML=html||empty;el.classList.toggle('empty-state',!html)}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString('pt-BR')}
window.removeItem=(type,id)=>{state[type]=state[type].filter(x=>x.id!==id);save()};window.markPaid=id=>{const d=state.debts.find(x=>x.id===id);if(d){d.paid=true;d.paidAt=today();save()}};
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.open).showModal()));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('#debtFilter').addEventListener('change',render);
$('#debtForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.debts.unshift({id:uid(),name:f.get('name'),amount:Number(f.get('amount')),dueDate:f.get('dueDate'),installment:f.get('installment'),installments:Number(f.get('installments')||1),note:f.get('note'),paid:false});e.target.reset();e.target.closest('dialog').close();save()});
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.expenses.unshift({id:uid(),name:f.get('name'),amount:Number(f.get('amount')),category:f.get('category')});e.target.reset();e.target.closest('dialog').close();save()});
$('#incomeForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.incomes.unshift({id:uid(),name:f.get('name'),amount:Number(f.get('amount'))});e.target.reset();e.target.closest('dialog').close();save()});
$('#investmentForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.investments.unshift({id:uid(),name:f.get('name'),amount:Number(f.get('amount')),type:f.get('type')});e.target.reset();e.target.closest('dialog').close();save()});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();