const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const today=()=>new Date().toISOString().slice(0,10);const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);const formatDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'Sem prazo';const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const sum=a=>a.reduce((t,x)=>t+Number(x.amount||0),0);
const state=JSON.parse(localStorage.getItem('finanx:data')||'{}');for(const k of ['debts','expenses','incomes','investments','assets','goals'])if(!Array.isArray(state[k]))state[k]=[];
function save(){localStorage.setItem('finanx:data',JSON.stringify(state));render()}
function debtStatus(d){if(d.paid)return'paid';return d.dueDate<today()?'overdue':'pending'}
function renderList(el,html,empty){el.innerHTML=html||empty;el.classList.toggle('empty-state',!html)}
function render(){const filter=$('#debtFilter').value;const overdue=state.debts.filter(d=>debtStatus(d)==='overdue'),pending=state.debts.filter(d=>debtStatus(d)==='pending'),paid=state.debts.filter(d=>debtStatus(d)==='paid'),debts=state.debts.filter(d=>filter==='all'||debtStatus(d)===filter);const inv=sum(state.investments),assets=sum(state.assets),exp=sum(state.expenses),inc=sum(state.incomes),open=sum([...overdue,...pending]),paidVal=sum(paid),allDebt=open+paidVal,proj=inc-exp-open,net=assets+inv-open;
$('#overdueTotal').textContent=money(sum(overdue));$('#overdueCount').textContent=`${overdue.length} conta${overdue.length===1?'':'s'}`;$('#pendingTotal').textContent=money(sum(pending));$('#pendingCount').textContent=`${pending.length} conta${pending.length===1?'':'s'}`;$('#paidTotal').textContent=money(paidVal);$('#paidCount').textContent=`${paid.length} conta${paid.length===1?'':'s'}`;$('#netWorthTotal').textContent=money(net);$('#assetsTotal').textContent=money(assets);$('#investmentTotal').textContent=money(inv);$('#investmentsTotal2').textContent=money(inv);$('#expensesTotal').textContent=money(exp);$('#incomeTotal').textContent=money(inc);$('#monthlyExpenseSummary').textContent=money(exp);$('#debtSummary').textContent=money(open);$('#projectedTotal').textContent=money(proj);$('#balanceLabel').textContent=money(proj);
let score=100;if(overdue.length)score-=Math.min(45,overdue.length*12);if(inc>0&&exp/inc>.7)score-=20;if(open>inc&&inc>0)score-=20;if(inv+assets>0)score+=5;score=Math.max(0,Math.min(100,score));$('#healthScore').textContent=score;
const freedom=allDebt?Math.round(paidVal/allDebt*100):0;$('#freedomPercent').textContent=`${freedom}%`;$('#freedomBar').style.width=`${freedom}%`;$('#debtPaidProgress').textContent=money(paidVal);$('#debtOpenProgress').textContent=money(open);const next=[...overdue,...pending].sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];$('#debtInsight').textContent=next?(debtStatus(next)==='overdue'?`Prioridade máxima: ${next.name} está atrasada. Quite ou negocie ${money(next.amount)}.`:`Próximo compromisso: ${next.name}, ${money(next.amount)}, vence em ${formatDate(next.dueDate)}.`):state.debts.length?'Parabéns: você não tem dívidas abertas cadastradas.':'Cadastre suas dívidas para o FinanX montar sua prioridade.';
renderList($('#debtsList'),debts.map(d=>{const st=debtStatus(d),part=d.installment==='yes'?` • ${d.installments}x de ${money(Number(d.amount)/Number(d.installments||1))}`:'';return `<div class="list-item ${st}"><div><div class="item-title">${esc(d.name)}</div><div class="item-meta">Vence ${formatDate(d.dueDate)}${part}${d.note?` • ${esc(d.note)}`:''}</div></div><div class="item-value">${money(d.amount)}<div class="item-meta">${st==='overdue'?'ATRASADO':st==='pending'?'A PAGAR':'PAGO'}</div></div><div class="item-actions">${!d.paid?`<button class="mini success" onclick="markPaid('${d.id}')">Marcar pago</button>`:''}<button class="mini danger" onclick="removeItem('debts','${d.id}')">Excluir</button></div></div>`}).join(''),'Nenhuma dívida encontrada.');
renderList($('#expensesList'),state.expenses.map(x=>`<div class="list-item"><div><div class="item-title">${esc(x.name)}</div><div class="item-meta">${esc(x.category)}</div></div><div class="item-value">${money(x.amount)}</div><div class="item-actions"><button class="mini danger" onclick="removeItem('expenses','${x.id}')">Excluir</button></div></div>`).join(''),'Nenhum gasto mensal cadastrado.');
renderList($('#investmentsList'),state.investments.map(x=>`<div class="list-item"><div><div class="item-title">${esc(x.name)}</div><div class="item-meta">${esc(x.type)}</div></div><div class="item-value">${money(x.amount)}</div><div class="item-actions"><button class="mini danger" onclick="removeItem('investments','${x.id}')">Excluir</button></div></div>`).join(''),'Nenhum investimento cadastrado.');
renderList($('#assetsList'),state.assets.map(x=>`<div class="list-item"><div><div class="item-title">${esc(x.name)}</div><div class="item-meta">${esc(x.type)}</div></div><div class="item-value">${money(x.amount)}</div><div class="item-actions"><button class="mini danger" onclick="removeItem('assets','${x.id}')">Excluir</button></div></div>`).join(''),'Nenhum patrimônio cadastrado.');
renderList($('#goalsList'),state.goals.map(g=>{const pct=g.target?Math.min(100,Math.round(Number(g.current||0)/Number(g.target)*100)):0;return `<div class="goal-item"><div class="section-head"><div><div class="item-title">${esc(g.name)}</div><div class="item-meta">${money(g.current)} de ${money(g.target)} • ${formatDate(g.dueDate)}</div></div><strong>${pct}%</strong></div><div class="progress"><span style="width:${pct}%"></span></div><div class="item-actions"><button class="mini success" onclick="addGoalValue('${g.id}')">+ valor</button><button class="mini danger" onclick="removeItem('goals','${g.id}')">Excluir</button></div></div>`}).join(''),'Nenhuma meta cadastrada.');
const upcoming=[...state.debts.filter(d=>!d.paid)].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5);renderList($('#calendarList'),upcoming.map(d=>`<div class="calendar-item ${debtStatus(d)}"><span>${formatDate(d.dueDate)}</span><div><strong>${esc(d.name)}</strong><small>${money(d.amount)}</small></div></div>`).join(''),'Nenhum vencimento próximo.')}
window.removeItem=(type,id)=>{state[type]=state[type].filter(x=>x.id!==id);save()};window.markPaid=id=>{const d=state.debts.find(x=>x.id===id);if(d){d.paid=true;d.paidAt=today();save()}};window.addGoalValue=id=>{const g=state.goals.find(x=>x.id===id);if(!g)return;const v=prompt(`Quanto deseja adicionar à meta “${g.name}”?`,'0');if(v!==null&&!isNaN(Number(v))&&Number(v)>0){g.current=Number(g.current||0)+Number(v);save()}};
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.open).showModal()));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('#debtFilter').addEventListener('change',render);
const bind=(id,type,map)=>$(id).addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state[type].unshift({id:uid(),...map(f)});e.target.reset();e.target.closest('dialog').close();save()});
bind('#debtForm','debts',f=>({name:f.get('name'),amount:Number(f.get('amount')),dueDate:f.get('dueDate'),installment:f.get('installment'),installments:Number(f.get('installments')||1),note:f.get('note'),paid:false}));bind('#expenseForm','expenses',f=>({name:f.get('name'),amount:Number(f.get('amount')),category:f.get('category')}));bind('#incomeForm','incomes',f=>({name:f.get('name'),amount:Number(f.get('amount'))}));bind('#investmentForm','investments',f=>({name:f.get('name'),amount:Number(f.get('amount')),type:f.get('type')}));bind('#assetForm','assets',f=>({name:f.get('name'),amount:Number(f.get('amount')),type:f.get('type')}));bind('#goalForm','goals',f=>({name:f.get('name'),target:Number(f.get('target')),current:Number(f.get('current')||0),dueDate:f.get('dueDate')}));
let deferredPrompt;const installBtn=$('#installBtn');const standalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;const syncInstallButton=()=>installBtn.classList.toggle('hidden',standalone()||!deferredPrompt);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;syncInstallButton()});window.addEventListener('appinstalled',()=>{deferredPrompt=null;syncInstallButton()});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;syncInstallButton()});if(standalone())installBtn.classList.add('hidden');
if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await registration.update()}catch(error){console.error('Falha ao registrar service worker:',error)}});render();